//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MoldControlEntities : DbContext
    {
        public MoldControlEntities()
            : base("name=MoldControlEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<td_inspection> td_inspection { get; set; }
        public DbSet<td_issue> td_issue { get; set; }
        public DbSet<td_ledger> td_ledger { get; set; }
        public DbSet<td_mold> td_mold { get; set; }
        public DbSet<td_tran> td_tran { get; set; }
        public DbSet<tm_inspection> tm_inspection { get; set; }
        public DbSet<tm_mold_type> tm_mold_type { get; set; }
        public DbSet<tm_status> tm_status { get; set; }
    }
}
