//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class td_issue
    {
        public string mold_code { get; set; }
        public string cavity_no { get; set; }
        public string machine_no { get; set; }
        public Nullable<System.DateTime> date_out { get; set; }
        public Nullable<int> qty { get; set; }
        public string appearance { get; set; }
        public string issue_by { get; set; }
        public Nullable<System.DateTime> date_in { get; set; }
        public string receive_by { get; set; }
    }
}
