//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class td_inspection
    {
        public string mold_code { get; set; }
        public string cavity_no { get; set; }
        public byte inspection_id { get; set; }
        public bool result { get; set; }
        public string description { get; set; }
    
        public virtual td_ledger td_ledger { get; set; }
        public virtual tm_inspection tm_inspection { get; set; }
    }
}
