//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class td_mold
    {
        public td_mold()
        {
            this.td_ledger = new HashSet<td_ledger>();
        }
    
        public string mold_code { get; set; }
        public byte mold_type { get; set; }
        public string item_code { get; set; }
        public string location { get; set; }
        public string mold_diameter { get; set; }
        public string unit { get; set; }
        public System.DateTime create_dt { get; set; }
        public string create_by { get; set; }
        public Nullable<System.DateTime> update_dt { get; set; }
        public string update_by { get; set; }
    
        public virtual ICollection<td_ledger> td_ledger { get; set; }
        public virtual tm_mold_type tm_mold_type { get; set; }
    }
}
