//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class td_tran
    {
        public string mold_code { get; set; }
        public string cavity_no { get; set; }
        public byte status_id { get; set; }
        public System.DateTime act_dt { get; set; }
        public string act_by { get; set; }
    
        public virtual tm_status tm_status { get; set; }
    }
}
