//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tm_inspection
    {
        public tm_inspection()
        {
            this.td_inspection = new HashSet<td_inspection>();
        }
    
        public byte inspection_id { get; set; }
        public string inspection_name { get; set; }
        public bool active { get; set; }
    
        public virtual ICollection<td_inspection> td_inspection { get; set; }
    }
}
