//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tm_mold_type
    {
        public tm_mold_type()
        {
            this.td_mold = new HashSet<td_mold>();
        }
    
        public byte mold_type { get; set; }
        public string mold_type_name { get; set; }
        public bool active { get; set; }
    
        public virtual ICollection<td_mold> td_mold { get; set; }
    }
}
