//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tm_status
    {
        public tm_status()
        {
            this.td_tran = new HashSet<td_tran>();
        }
    
        public byte status_id { get; set; }
        public string status_name { get; set; }
    
        public virtual ICollection<td_tran> td_tran { get; set; }
    }
}
